### ISSUE TITLE
ELMCIP Version 1.14

### ISSUE THREAD

**Issue by steinmb** [elmcip/elmcip#117]
Issues addressed in version 1.14 of ELMCIP. All these changes will be staged and tested on http://test.elmcip.net.
- [x] #133  Views data export - Garbage collection cache is not removed
- [x] #122 - Display of Label on Organization for Critical Writing Field should be emphasized (bold)
- [x] #121 - Platform/Software version history text: Not Displaying on node view
- [x] #114 - Redo of issue #102: Add data export views for Critical Writing presented at event
- [x] #112 - Install and configure CELL OAI-PMH module
- [x] #109 - Remove Drupal core Update module from production
- [x] #108 - Remove Styles module
- [x] #107 - RDF UI causes: Integrity constraint violation: 1048 Column 'bundle' cannot be null
- [x] #89 - Update or remove token_tweaks module
## Drupal core update
- Drupal 7.36 to 7.37 upgrade Commit: 8a06dfa
- Drupal security update SA-CORE-2015-002: Drupal 7.37 -> 7.38 commit: 92e4819 
## Modules

Tested on update though might cause side effects we did not pick up on update. Changes to these also can cause changes to exported settings tracked by the Features module.
- Views (Security update) 7.x-3.10 -> 7.x-3.11 commit: ce18ba8
