### ISSUE TITLE
ELMCIP Version 1.15

### ISSUE THREAD

**Issue by steinmb** [elmcip/elmcip#135]
Issues addressed in version 1.15 of ELMCIP. All these changes will be staged and tested on http://test.elmcip.net.
- [x] #136 Creative work date views
- [x] #134 - Extra spaces in author node title 
- [ ] #112 - Install and configure CELL OAI-PMH module
- [x] #90  - Remove Submit to ELMCIP Anthology
## Drupal core update
- None
## Modules updates

Tested on update though might cause side effects we did not pick up on update. Changes to these also can cause changes to exported settings tracked by the Features module.
- commit d12ff9a29bc648f0f45e1f50a2fa6980dfcf774e Security: Views Bulk Operations 7.x-3.2 to 7.x-3.3 SA-CONTRIB-2015-131
- commit 1da447006a07b6acfb2914c7ae2596466e39f71d Module update: advanced_help 7.x-1.2 to 7.x-1.3
  - Turn on development settings now enable this module
  - Release note: https://www.drupal.org/node/2494535
