### ISSUE TITLE
ELMCIP Version 1.16

### ISSUE THREAD

**Issue by steinmb** [elmcip/elmcip#139]
Issues addressed in the next version of ELMCIP. All these changes will be staged and tested on http://test.elmcip.net during development.
- [x] #149 - View "Works presented" expose export function to anonymous users.
- [x] #147 - View "Critical writing presented" - not accessible to anonymous users.
- [x] #144 - Make date columns sortable in views.
- [x] #143 - Year missing from Creative Works on Author Content-Type
- [x] #141 - Increase contrast to hyperlinks. 
- [x] #140 - Enable feature module ELMCIP permissions (elmcip_permissions).
- [x] #126 - Referenced Platforms not displaying on Research Collection
- [x] #125 - Repository Field not Showing on Creative Works
- [x] #123 - Update work_nid_data data export view to include language and platform in exported data set
- [x] #119 - Hyperlink in platform/Software help text for creative and critical - work open wrong link.
- [ ] #112  - Install and configure CELL OAI-PMH module
- [x] #75 - Migrate Publisher record to entity reference.
## Drupal core updates
- 33903700d831f5fc3c32cf5502ff54b17739b10d Drupal 7.39 security update
## Modules updates
- 2fcc83577479a1dad3229b1374af79bc960e520a Ctools 7.x-1.7 -> 7.x-1.9

Tested on update though might cause side effects we did not pick up on update. Changes to these also can cause changes to exported settings tracked by the Features module.
