### ISSUE TITLE
ELMCIP Version 1.17

### ISSUE THREAD

**Issue by steinmb** [elmcip/elmcip#142]
Issues addressed in the next version of ELMCIP. All these changes will be staged and tested on http://test.elmcip.net during development.
- [ ]  Remove Views bulk operations and views created with it? #137 
- [ ]  Change Designation for Critical Writing that Appears on Critical Writing #131 
- [ ] #130 - Referenced Creative Works Duplicated on Critical Writing.
- [ ] #113 - Author links missing on front page views for critical writing, work.
- [ ] #112  - Install and configure CELL OAI-PMH module.
- [ ] #93 - Provide export of references.
- [ ] #91 - Replace field_number with a real date field.
- [x] #52 - View (content_by_contributor) listing users edits/revisions not fully working.
- [ ] #64 - Improve look of tables.
- [ ] #45 - Flickr slideshow element overflow container.
- [ ] #2 - Move from media field deprecated field type to regular file field.
## Drupal core updates
- None
## Modules updates

Tested on update though might cause side effects we did not pick up on update. Changes to these also can cause changes to exported settings tracked by the Features module.
- None
## How to test

This version (master) will be staged on http://test.elmcip.net
