### ISSUE TITLE
Front Page Layout--Tracking Issue

### ISSUE THREAD

**Issue by AlvaroSeica** [elmcip/elmcip#185]
This is an ongoing list for us to list issues we want to deal with at a certain point in terms of changes in the front page:

- [ ] Blocks--define which
- [ ] Thumbnails of 5 records changing: issue #47 (5 records selected here)
- [x] Add "Create New Record" to the Menu Bar: issue #49
- [x] Twitter Widget User @ELMCIP Timeline: issue #38 HTML code:  

```

<a class="twitter-timeline"  href="https://twitter.com/ELMCIP" data-widget-id="727438837933285377">Tweets by @elmcip </a>
            <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>

```
