### ISSUE TITLE
Upgrade media major version

### ISSUE THREAD

**Issue by steinmb** [elmcip/elmcip#2]
Media field type is now deprecated. To allow us to move to Media 7.x-2.x branch we need to first drop/move away from this field type.
## Tasks
- [x] Upgrade media and related modules to 7.x-2.x
- [x] ~~Migrate data from legacy field type to file/image field type.~~ Addressed in #186
- [ ] Monkey work. Remove bad and broken files from system. See details bellow.
## Remove broken media data

Broken data flushed out during update. These should be deleted from http://elmcip.net directly from the UI after site have been upgraded.

http://elmcip.net/file/[fid] Replace [fid] with numeric id from list and delete as normal.

```
    fid: 800
    fid: 43267
    fid: 42647
    fid: 42486
    fid: 42430
    fid: 42429
    fid: 2351
    fid: 1649
    fid: 1588
    fid: 1570
    fid: 1361
    fid: 868
    fid: 867
```
## How to test
- Check that existing images, Flickr, Vimeo and Youtube display correctly
- Check that adding, removing, uploading of new media elements work as normal
- Check that media browser work as expected, including filtering
- Check that http://elmcip.dev/admin/content/file work
### Docs
- https://www.drupal.org/node/1349058
