### ISSUE TITLE
[Meta] Remove all view modes no longer needed

### ISSUE THREAD

**Issue by steinmb** [elmcip/elmcip#242]
Noticed this working on #229. 
#### Example

<img width="917" alt="cabaret_voltage___elmcip" src="https://cloud.githubusercontent.com/assets/683617/19324192/a63877a2-90c0-11e6-91ea-f8fd185fc41a.png">

## Suggested fix
-  [x] Vertical margin should always be the same as line height. Here 21px (1.5em).
- [x] Last paragraph should no have margins. This break flow many places
- [x] Move meta data fields into separate wrapper that is set apart from the rest of the content. Perhaps use double margin around it.
- [x] Multi value media type fields (images and videos) lack margins. Half margins might work.

## Content types

- [x] #305 Story
- [x] Page
- [x] Creative Work
- [x] #339 Critical Writing
- [x] #338 Databases and Archives
- [x] #256 Event
- [x] #329 Organizations
- [x] #337 Person
- [x] Platform/Software
- [x] Publisher
- [x] Research Collection
- [x] Teaching Resource

## Follow up issues

After we have removed view mode clutter created by DS module should we address issue #315 to replace the module.

**Comment by steinmb** [comment]
Let's see what we can break. Cleaned up creative work view modes. Any one left is default.

commit c38e24d4d44cf47c89f1649097ccd9fb299c3c36 (HEAD -> master, origin/master, origin/HEAD)
Author: Stein Magne Bjorklund <steinmb@smbjorklund.com>
Date:   Wed Apr 18 21:55:58 2018 +0100

    Issue 242 Creative work remove view mode full, token, data_export and teaser

    - View modes no longer needed.
    - Update layout, fields, and field groups.

**Comment by steinmb** [comment]
Addressing software/platform while at it.

commit d4d9c0f296fe195e88a0c015f1c78b05949f6e23 (HEAD -> master, origin/master, origin/HEAD)
Author: Stein Magne Bjorklund <steinmb@smbjorklund.com>
Date:   Thu Apr 19 14:02:50 2018 +0100

    Issue 242 remove Platform software full node view mode

    - Not needed, default is enough.
    - Added field group used for meta data.

**Comment by steinmb** [comment]
Cleaning up publishers

commit f64f8bf4dac51f6c3aeac0423317248c583d2888 (HEAD -> master, origin/master, origin/HEAD)
Author: Stein Magne Bjorklund <steinmb@smbjorklund.com>
Date:   Thu Apr 19 17:02:48 2018 +0100

    Issue 242 Removed publisher full view mode

    - No longer needed. Default is all we need.
    - Meta data wrapped into a field group that apply default
    styles.

**Comment by steinmb** [comment]
Research collections

commit b580b7cec0fdc7a62df066abeb4be8bb90424874 (HEAD -> master, origin/master, origin/HEAD)
Author: Stein Magne Bjorklund <steinmb@smbjorklund.com>
Date:   Thu Apr 19 18:01:02 2018 +0100

    Issue 242 Removed no longer needed view modes

    - Meta data stored instide a field wrapper to ease styling`

**Comment by steinmb** [comment]
The last one, Teaching Resources

commit 929a2c0d5f0efddd314ac01e1dac7728ca1c2676 (HEAD -> master, origin/master, origin/HEAD)
Author: Stein Magne Bjorklund <steinmb@smbjorklund.com>
Date:   Fri Apr 20 16:50:14 2018 +0100

    Issue 242 Remove view modes and field groups

    - Teaching Resource view modes removed. Default is all we need.
    - Removed and cleaned up field groups.
