### ISSUE TITLE
Migrate from Norstore to NIRD infrastructure

### ISSUE THREAD

**Issue by steinmb** [elmcip/elmcip#341]
ELMCIP web application is going to be moved into NIRD infrastructure, in ~~October 2017~~ ~~April 2018~~ May 2018.

## Tasks

* [x] ~~Create Docker containers for web application.~~
* [x] Move anthology.elmcip.net
* [x] Our cert. has at two occurrences "gone away". Config file get overwritten by default template.
* [x] Drupal cron tasks config
* [x] Syslog demon config
* [x] Mail service

## Docker containers needed

1. Apache MPM event
1. PHP FPM 7.1
1. Mysql / MariaDB
1. ~~Introduce Solr as search backend?~~

**Comment by steinmb** [comment]
To make sure PHP 7.0 work for elmcip have I now switched my local dev. environment to 7.0. I also added a point about us finally switching search backend to [Solr](https://lucene.apache.org/solr/).

**Comment by steinmb** [comment]
@elmcip have to gotten any information about this on mail?

**Comment by steinmb** [comment]
Take II in moving to NIRD in progress.

**Comment by steinmb** [comment]
NIRD is still struggling getting SSL in place. Nothing we can do then wait.

**Comment by steinmb** [comment]
And we are up again. They needed to hack SSL to get it running, meaning they are going continue tomorrow, creating a solution that works the right way. Expect a little more downtime.

**Comment by steinmb** [comment]
YAY!
