### ISSUE TITLE
[META] Cell project merge

### ISSUE THREAD

**Issue by steinmb** [elmcip/elmcip#462]
We are taking over development and maintenance of http://cellproject.net. All work is happening in https://github.com/smbjorklund/cellproject/issues until it is safe to include it as a Drupal multisite instance.

There is multiple code repositories. They are all private but multiple Cell-related persons have access. Let we know if you do not have access but would like to.

## Test and merge steps

1. [x] Update and clean out not used and needed modules, lib. and themes.
1. [x] Stage in our test env. on NIRD
1. [x] Create Cell Solr core, configure instance to use ELMCIP Solr instance.
1. [x] Test and convert and enable Multi-byte UTF-8 support.
1. [x] Stage cellproject.net in production
1. [x] Update NIRD routing to handle domain cellproject.net traffic.

## Post production
1. [ ] Address the failing data migration
1. [ ] Remove ELMCIP and cellproject.net module duplications.

## CELL test site

* https://cell.elmcip.net

## Stage existing installations

All code are gitmodules and you need to run: `git submodule update --init` again to get the code.

**Comment by steinmb** [comment]
Locally we have a cleaned up site running. Last changes to Cell official repos and and ELMCIP allowed us to add Cell as a git submodule. Looks OK though more testing remains to be done, and I am waiting (still) for a new and empty db. on test.elmcip.net allowing us to test stage it to.

c13afb2 Cellproject main theme as submodue
0e49cbd Cellproject symbolic links
833f61d Sync up Cell project
8fa8d89 Cellproject private storage area

**Comment by steinmb** [comment]
We are still waiting on a db. to stage into. Notified NIRD on this. It is a few minutes job on their side.

**Comment by steinmb** [comment]
We are experiencing problems with the `test.elmcip.net` server. It might or might not have anything to do with the work on cellnetwork db. that they started on today.

**Comment by steinmb** [comment]
Confirm that https://test.elmcip.net is up again, they are still working on the CELL db.

**Comment by steinmb** [comment]
@elmcip https://cell.elmcip.net is enabled in test tough.

**Comment by steinmb** [comment]
@elmcip - Cell now have a separate Solr core. Upgrades cell from the old Solr 3.6.2 (2013) to 7.x. Solr 3.6.x reached end of life many many years ago and is unsupported.

**Comment by steinmb** [comment]
Looking good, closing issue
