### ISSUE TITLE
[META] Move from old node referance (drupal 6 legacy) to entity reference

### ISSUE THREAD

**Issue by steinmb** [elmcip/elmcip#5]
This will very effectively break every view that use this field plugin. Replace all of them and and update all broken views without data loss.
### Breaking this mega issue down into smaller issues:
- [x] #59 Migrate Person record to entity reference
- [x] #65 Migrate Event record to entity reference.
- [x] #66 Class Group
- [x] #67 Creative Work
- [x] #71 Critical Writing
- [x] #73 Databases and Archives
- [x] ~~Notebook~~
- [x] #234 Notebook entry
- [x] ~~Organizations~~
- [x] ~~Page~~
- [x] ~~Panel~~
- [x] ~~Person~~
- [x] #74 Platform/Software
- [x] #75 Publisher
- [x] #76 Research Collection
- [x] ~~Story~~
- [x] #77 Teaching Resource
## Fix (post migration)
- [x] After the migration is done, remove any CSS belong to the old node ref. fields no longer in use.
- [x] Disable and uninstall reference module.
