### ISSUE TITLE
provide export of references

### ISSUE THREAD

**Issue by schreibpilot** [elmcip/elmcip#93]
This issue also addresses issue #83. Once upon a time we offered to export views, for a bunch of references, this does not work any longer.
## Changes to be done

There should be export opportunities for the following.
- [x] Person Record. Export all references provided in a person record example: http://test.elmcip.net/person/scott-rettberg (We are only exporting Creative work and Critical Writing)
- [ ] #192 Critical Writing record (export creative works is provided). we should add: export "critical writing referenced"; "Critical writing that references this" and any other view that may be applicable, such as for example "Teaching Resource using this Critical Writing".
- [ ] #83 Add data export view show critical writing presented at an event. We currently have a data export view to show what works were presented at a given event but not to show what critical writing was presented. We should create a data export view to pull down that data as well.
- [x] #101 Add data export views to Person for works by person, critical writing by person.

Not sure what other views may be applicable.

Creative Work records should also allow to export any references that may be applicable when it comes to the references that come along with creative works, such as for example:

"Critical writing that references this work"
"Teaching Resource that references this work"
"Research Collection that references this work"
## How to test

xxxxx xxxx xxxx
